### ISSUE TITLE
Negating glob patterns not usable in AgentInjector resource

### ISSUE THREAD

**Issue by lkallas** [Contrast-Security-OSS/agent-operator#189]
## Background
Consider a case where there are many pods running with main container and some sidecar container (e.g. db-proxy) inside a Kubernetes cluster.

Contrast Kuberentes operator `AgentInjector` [custom resource](https://docs.contrastsecurity.com/en/agent-operator-configuration.html) allows one to specify to which containers the agent is injected to inside a pod.  

`spec.selector.images` allows specifying a glob pattern which is used to find a match.

I can see that there is C# [Glob package](https://github.com/Contrast-Security-OSS/agent-operator/blob/master/src/Contrast.K8s.AgentOperator/Contrast.K8s.AgentOperator.csproj#L39) in use.

## Problem
In my case, I would like to inject `nodejs` agent into every container in many pods. But I do not want to inject it to `db-proxy` container which is not a `nodejs` workload and also does not need any instrumentation.

I struggle to find a good glob pattern for this purpose.  
Seems that there actually isn't one for my case - well, [Glob](https://github.com/kthompson/glob) package does not implement it (not correctly at least IMO).

So to illustrate this problem, take this small program snippet I used to determine the glob pattern for my case.
I would like to match any Docker image that does not have "some-proxy" in it's name using negating pattern.

```csharp
using System;
using GlobExpressions;

public interface IGlobMatcher
{
	bool Matches(string pattern, string value);
}

public class GlobMatcher : IGlobMatcher
{
	public bool Matches(string pattern, string value)
	{
		var glob = new Glob(pattern, GlobOptions.CaseInsensitive | GlobOptions.Compiled);
		return glob.IsMatch(value);
	}
}

public class Program
{
	public static void Main()
	{
		var matcher = new GlobMatcher();		
		var pattern = "!(*some-proxy*)";  // Trying to use negating pattern
		
		var result1 = matcher.Matches(pattern, "europe-docker.pkg.dev/project/docker-images/whatever:latest"); // This should return True
		Console.WriteLine(result1); // False
		
		var result2 = matcher.Matches(pattern, "europe-docker.pkg.dev/project/docker-images/some-proxy:latest"); // This should return False
		Console.WriteLine(result2); // False
	}
}
```

I see that you do not have a such test-case either in [your tests](https://github.com/Contrast-Security-OSS/agent-operator/blob/master/tests/Contrast.K8s.AgentOperator.Tests/Core/Reactions/Injecting/GlobMatcherTests.cs).

## Workaround
The only workaround right now is to specify each image name in the manifest:

```yaml
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: contrast-agent-injector
  namespace: somenamespace
spec:
  enabled: true
  version: latest
  type: nodejs
  selector:
    images:
      - "*important-web*"
      - "*some-other-web*"
      - "*restful-api*"
    labels:
      - name: contrast
        value: enabled
```

Could you assist/profide a fix?
@Silvenga @gamingrobot 

Thank you!
